#!/usr/bin/env python3
"""Generate all .po files and compile them to .mo for wack-lockscreen-clock."""

import os, subprocess

DOMAIN = "wack-lockscreen-clock@rinzler69-wastaken.github.com"
EXT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PO_DIR  = os.path.join(EXT_DIR, "po")
LOC_DIR = os.path.join(EXT_DIR, "locale")

# Core/Existing translations
MORE = {'es': 'más', 'fr': 'plus', 'de': 'mehr', 'it': 'altro', 'pt': 'mais', 'ru': 'ещё', 'zh': '更多', 'ja': 'さらに', 'ko': '더 보기', 'ar': 'المزيد', 'hi': 'अधिक', 'tr': 'daha fazla', 'nl': 'meer', 'pl': 'więcej', 'sv': 'mer', 'da': 'mere', 'no': 'mer', 'fi': 'lisää', 'el': 'περισσότερα', 'he': 'עוד', 'id': 'lagi', 'th': 'เพิ่มเติม', 'vi': 'thêm'}

TOGGLE = {'es': 'Presiona Shift + N para ver notificaciones', 'fr': 'Appuyez sur Maj+N pour voir les notifications', 'de': 'Shift + N drücken, um Benachrichtigungen anzuzeigen', 'it': 'Premi Maiusc + N per visualizzare le notifiche', 'pt': 'Pressione Shift + N para ver as notifications', 'ru': 'Нажмите Shift + N для просмотра уведомлений', 'zh': '按 Shift + N 查看通知', 'ja': 'Shift + N で通知を表示', 'ko': 'Shift + N을 눌러 알림 보기', 'ar': 'اضغط Shift + N لعرض الإشعارات', 'hi': 'सूचनाएं देखने के लिए Shift + N दबाएं', 'tr': "Bildirimleri görmek için Shift + N'ye basın", 'nl': 'Druk op Shift + N om meldingen te bekijken', 'pl': 'Naciśnij Shift + N, aby wyświetlić powiadomienia', 'sv': 'Tryck på Shift + N för att visa aviseringar', 'da': 'Tryk på Shift + N for at se notifikationer', 'no': 'Trykk Shift + N for å se varsler', 'fi': 'Paina Shift + N nähdäksesi ilmoitukset', 'el': 'Πατήστε Shift + N για προβολή ειδοποιήσεων', 'he': 'הקש Shift + N כדי לראות התראות', 'id': 'Tekan Shift + N untuk melihat notifikasi', 'th': 'กด Shift + N เพื่อดูการแจ้งเตือน', 'vi': 'Nhấn Shift + N để xem thông báo'}

INHIBIT = {
    'es': 'Suspensión impedida por un proceso activo',
    'fr': 'Mise en veille empêchée par un processus actif',
    'de': 'Bereitschaft durch einen aktiven Prozess verhindert',
    'it': 'Sospensione impedita da un processo attivo',
    'pt': 'Suspensão impedida por um processo ativo',
    'ru': 'Режим ожидания заблокирован активным процессом',
    'zh': '系统挂起被活动进程阻止',
    'ja': 'アクティブなプロセスによりサスペンドが妨げられています',
    'ko': '활성 프로세스로 인해 절전 모드 진입이 방지되었습니다',
    'ar': 'تم منع التعليق بواسطة عملية نشطة',
    'hi': 'एक सक्रिय प्रक्रिया द्वारा निलंबن रोका गया',
    'tr': 'Askıya alma etkin bir işlem tarafından engellendi',
    'nl': 'Slaapmodus verhinderd door een actief proces',
    'pl': 'Uśpienie zablokowane przez aktywny proces',
    'sv': 'Vänteläge förhindras av en aktiv process',
    'da': 'Hviletilstand forhindres af en aktiv proces',
    'no': 'Hvilemodus forhindres av en aktiv prosess',
    'fi': 'Valmiustila estetty aktiivisen prosessin toimesta',
    'el': 'Η αναστολή λειτουργίας αποτράπηκε από μια ενεργή διεργασία',
    'he': 'ההשהיה נמנעה על ידי תהליך פעיל',
    'id': 'Mode tidur dicegah oleh proses aktif',
    'th': 'การพักเครื่องถูกป้องกันโดยกระบวนการที่ทำงานอยู่',
    'vi': 'Việc tạm dừng bị ngăn cản bởi một quy trình đang hoạt động'
}

# Prefs translations
PREFS_STRINGS = {
    "1 minute": {
        "es": "1 minuto",
        "fr": "1 minute",
        "de": "1 Minute",
        "it": "1 minuto",
        "pt": "1 minuto",
        "ru": "1 минута",
        "zh": "1分钟",
        "ja": "1分",
        "ko": "1분",
        "ar": "1 دقيقة",
        "hi": "1 मिनट",
        "tr": "1 dakika",
        "nl": "1 minuut",
        "pl": "1 minuta",
        "sv": "1 minut",
        "da": "1 minut",
        "no": "1 minutt",
        "fi": "1 minuutti",
        "el": "1 λεπτό",
        "he": "דקה אחת",
        "id": "1 menit",
        "th": "1 นาที",
        "vi": "1 phút"
    },
    "10 minutes": {
        "es": "10 minutos",
        "fr": "10 minutes",
        "de": "10 Minuten",
        "it": "10 minuti",
        "pt": "10 minutos",
        "ru": "10 минут",
        "zh": "10分钟",
        "ja": "10分",
        "ko": "10분",
        "ar": "10 دقائق",
        "hi": "10 मिनटों",
        "tr": "10 dakika",
        "nl": "10 minuten",
        "pl": "10 minut",
        "sv": "10 minuter",
        "da": "10 minutter",
        "no": "10 minutter",
        "fi": "10 minuuttia",
        "el": "10 λεπτά",
        "he": "10 דקות",
        "id": "10 menit",
        "th": "10 นาที",
        "vi": "10 phút"
    },
    "15 minutes": {
        "es": "15 minutos",
        "fr": "15 minutes",
        "de": "15 Minuten",
        "it": "15 minuti",
        "pt": "15 minutos",
        "ru": "15 минут",
        "zh": "15分钟",
        "ja": "15分",
        "ko": "15분",
        "ar": "15 دقيقة",
        "hi": "15 मिनटों",
        "tr": "15 dakika",
        "nl": "15 minuten",
        "pl": "15 minut",
        "sv": "15 minuter",
        "da": "15 minutter",
        "no": "15 minutter",
        "fi": "15 minuuttia",
        "el": "15 λεπτά",
        "he": "15 דקות",
        "id": "15 menit",
        "th": "15 นาที",
        "vi": "15 phút"
    },
    "2 hours": {
        "es": "2 horas",
        "fr": "2 heures",
        "de": "2 Stunden",
        "it": "2 ore",
        "pt": "2 horas",
        "ru": "2 часа",
        "zh": "2小时",
        "ja": "2時間",
        "ko": "2시간",
        "ar": "ساعاتين",
        "hi": "2 घंटे",
        "tr": "2 saat",
        "nl": "2 uur",
        "pl": "2 godziny",
        "sv": "2 timmar",
        "da": "2 timer",
        "no": "2 timer",
        "fi": "2 tuntia",
        "el": "2 ώρες",
        "he": "2 שעות",
        "id": "2 jam",
        "th": "2 ชั่วโมง",
        "vi": "2 giờ"
    },
    "30 minutes": {
        "es": "30 minutos",
        "fr": "30 minutes",
        "de": "30 Minuten",
        "it": "30 minuti",
        "pt": "30 minutos",
        "ru": "30 минут",
        "zh": "30分钟",
        "ja": "30分",
        "ko": "30분",
        "ar": "30 دقيقة",
        "hi": "30 मिनट",
        "tr": "30 dakika",
        "nl": "30 minuten",
        "pl": "30 minut",
        "sv": "30 minuter",
        "da": "30 minutter",
        "no": "30 minutter",
        "fi": "30 minuuttia",
        "el": "30 λεπτά",
        "he": "30 דקות",
        "id": "30 menit",
        "th": "30 นาที",
        "vi": "30 phút"
    },
    "5 minutes": {
        "es": "5 minutos",
        "fr": "5 minutes",
        "de": "5 Minuten",
        "it": "5 minuti",
        "pt": "5 minutos",
        "ru": "5 минут",
        "zh": "5分钟",
        "ja": "5分",
        "ko": "5분",
        "ar": "5 دقائق",
        "hi": "5 मिनट",
        "tr": "5 dakika",
        "nl": "5 minuten",
        "pl": "5 minut",
        "sv": "5 minuter",
        "da": "5 minutter",
        "no": "5 minutter",
        "fi": "5 minuuttia",
        "el": "5 λεπτά",
        "he": "5 דקות",
        "id": "5 menit",
        "th": "5 นาที",
        "vi": "5 phút"
    },
    "60 minutes": {
        "es": "60 minutos",
        "fr": "60 minutes",
        "de": "60 Minuten",
        "it": "60 minuti",
        "pt": "60 minutos",
        "ru": "60 минут",
        "zh": "60分钟",
        "ja": "60分",
        "ko": "60분",
        "ar": "60 دقيقة",
        "hi": "60 मिनट",
        "tr": "60 dakika",
        "nl": "60 minuten",
        "pl": "60 minut",
        "sv": "60 minuter",
        "da": "60 minutter",
        "no": "60 minutter",
        "fi": "60 minuuttia",
        "el": "60 λεπτά",
        "he": "60 דקות",
        "id": "60 menit",
        "th": "60 นาที",
        "vi": "60 phút"
    },
    "Always Show User Widget (Cupertino)": {
        "es": "Mostrar siempre el widget de usuario (Cupertino)",
        "fr": "Toujours afficher le widget utilisateur (Cupertino)",
        "de": "Benutzer-Widget immer anzeigen (Cupertino)",
        "it": "Mostra sempre il widget utente (Cupertino)",
        "pt": "Sempre mostrar o widget do usuário (Cupertino)",
        "ru": "Всегда показывать виджет пользователя (Купертино)",
        "zh": "始终显示用户小部件 (库比蒂诺)",
        "ja": "ユーザー ウィジェットを常に表示 (クパチーノ)",
        "ko": "항상 사용자 위젯 표시(Cupertino)",
        "ar": "إظهار أداة المستخدم دائمًا (كوبرتينو)",
        "hi": "हमेशा उपयोगकर्ता विजेट दिखाएँ (क्यूपर्टिनो)",
        "tr": "Her Zaman Kullanıcı Widget'ını Göster (Cupertino)",
        "nl": "Gebruikerswidget altijd tonen (Cupertino)",
        "pl": "Zawsze pokazuj widżet użytkownika (Cupertino)",
        "sv": "Visa alltid användarwidget (Cupertino)",
        "da": "Vis altid brugerwidget (Cupertino)",
        "no": "Vis alltid brukerwidget (Cupertino)",
        "fi": "Näytä aina käyttäjän widget (Cupertino)",
        "el": "Να εμφανίζεται πάντα το γραφικό στοιχείο χρήστη (Cupertino)",
        "he": "הצג תמיד ווידג'ט למשתמש (קופרטינו)",
        "id": "Selalu Tampilkan Widget Pengguna (Cupertino)",
        "th": "แสดงวิดเจ็ตผู้ใช้เสมอ (คูเปอร์ติโน)",
        "vi": "Luôn hiển thị tiện ích người dùng (Cupertino)"
    },
    "Always shows user widget, hides notifications by default. Press Shift+N to show notifications.": {
        "es": "Muestra siempre el widget de usuario y oculta las notificaciones por defecto. Presione Shift+N para ver las notificaciones.",
        "fr": "Affiche toujours le widget utilisateur et masque les notifications par défaut. Appuyez sur Shift+N pour afficher les notifications.",
        "de": "Zeigt das Benutzer-Widget immer an und blendet Benachrichtigungen standardmäßig aus. Drücken Sie Shift+N, um Benachrichtigungen anzuzeigen.",
        "it": "Mostra sempre il widget utente, nasconde le notifiche per impostazione predefinita. Premi Shift+N per mostrare le notifiche.",
        "pt": "Mostra sempre o widget do usuário e oculta as notificações por padrão. Pressione Shift+N para exibir as notificações.",
        "ru": "Всегда показывать виджет пользователя, по умолчанию скрывая уведомления. Нажмите Shift+N для показа уведомлений.",
        "zh": "始终显示用户小部件，默认隐藏通知。按 Shift+N 显示通知。",
        "ja": "常にユーザーウィジェットを表示し、デフォルトで通知を非表示にします。Shift+N キーで通知を表示します。",
        "ko": "사용자 위젯을 항상 표시하고 기본적으로 알림을 숨깁니다. 알림을 보려면 Shift+N을 누르세요.",
        "ar": "يعرض دائمًا عنصر واجهة المستخدم للمستخدم، ويخفي الإشعارات افتراضيًا. اضغط على Shift+N لإظهار الإشعارات.",
        "hi": "हमेशा उपयोगकर्ता विजेट दिखाता है, डिफ़ॉल्ट रूप से सूचनाएं छुपाता है। सूचनाएं दिखाने के लिए Shift+N दबाएं।",
        "tr": "Kullanıcı widget'ını her zaman gösterir, bildirimleri varsayılan olarak gizler. Bildirimleri göstermek için Shift+N tuşlarına basın.",
        "nl": "Toont altijd de gebruikerswidget en verbergt standaard meldingen. Druk op Shift+N om meldingen weer te geven.",
        "pl": "Zawsze wyświetla widżet użytkownika, domyślnie ukrywając powiadomienia. Naciśnij Shift+N, aby wyświetlić powiadomienia.",
        "sv": "Visar alltid användarwidgeten, döljer aviseringar som standard. Tryck på Shift+N för att visa aviseringar.",
        "da": "Viser altid brugerwidgetten, skjuler notifikationer som standard. Tryk på Shift+N for at vise notifikationer.",
        "no": "Viser alltid brukerwidgeten, skjuler varsler som standard. Trykk Shift+N for å vise varsler.",
        "fi": "Näyttää aina käyttäjän widgetin, piilottaa ilmoitukset oletuksena. Näytä ilmoitukset painamalla Shift+N.",
        "el": "Εμφανίζει πάντα το γραφικό στοιχείο χρήστη, αποκρύπτοντας τις ειδοποιήσεις από προεπιλογή. Πατήστε Shift+N για να εμφανιστούν οι ειδοποιήσεις.",
        "he": "תמיד מציג את ווידג'ט המשתמש, ומסתיר התראות כברירת מחדل. לחץ על Shift+N כדי להציג התראות.",
        "id": "Selalu menampilkan widget pengguna dan menyembunyikan notifikasi secara default. Tekan Shift+N untuk menampilkan notifikasi.",
        "th": "แสดงวิดเจ็ตผู้ใช้เสมอ ซ่อนการแจ้งเตือนตามค่าเริ่มต้น กด Shift+N เพื่อแสดงการแจ้งเตือน",
        "vi": "Luôn hiển thị tiện ích người dùng, ẩn thông báo theo mặc định. Nhấn Shift+N để hiển thị thông báo."
},
    "Animations": {
        "es": "Animaciones",
        "fr": "Animations",
        "de": "Animationen",
        "it": "Animazioni",
        "pt": "Animações",
        "ru": "Анимации",
        "zh": "动画",
        "ja": "アニメーション",
        "ko": "애니메이션",
        "ar": "الرسوم المتحركة",
        "hi": "एनिमेशन",
        "tr": "Animasyonlar",
        "nl": "Animaties",
        "pl": "Animacje",
        "sv": "Animationer",
        "da": "Animationer",
        "no": "Animasjoner",
        "fi": "Animaatiot",
        "el": "Κινούμενα σχέδια",
        "he": "אנימציות",
        "id": "Animasi",
        "th": "ภาพเคลื่อนไหว",
        "vi": "Hoạt hình"
    },
    "Applied to the authentication prompt while it appears": {
        "es": "Se aplica al mensaje de autenticación mientras aparece.",
        "fr": "Appliqué à l'invite d'authentification lorsqu'elle apparaît",
        "de": "Wird auf die Authentifizierungsaufforderung angewendet, während sie angezeigt wird",
        "it": "Applicato alla richiesta di autenticazione mentre viene visualizzata",
        "pt": "Aplicado ao prompt de autenticação enquanto ele aparece",
        "ru": "Применяется к запросу аутентификации, пока он появляется.",
        "zh": "应用于出现的身份验证提示",
        "ja": "認証プロンプトが表示されている間、認証プロンプトに適用されます",
        "ko": "인증 프롬프트가 표시되는 동안 적용됩니다.",
        "ar": "يتم تطبيقه على موجه المصادقة أثناء ظهوره",
        "hi": "प्रमाणीकरण संकेत प्रकट होने पर उस पर लागू किया गया",
        "tr": "Göründüğü sırada kimlik doğrulama istemine uygulandı",
        "nl": "Toegepast op de authenticatieprompt terwijl deze verschijnt",
        "pl": "Stosowane do monitu o uwierzytelnienie, gdy się pojawia",
        "sv": "Tillämpas på autentiseringsprompten medan den visas",
        "da": "Anvendt på godkendelsesprompten, mens den vises",
        "no": "Brukes på autentiseringsmeldingen mens den vises",
        "fi": "Käytetään todennuskehotteessa, kun se näkyy",
        "el": "Εφαρμόζεται στο μήνυμα ελέγχου ταυτότητας ενώ εμφανίζεται",
        "he": "מוחל על בקשת האימות בזמן שהיא מופיעה",
        "id": "Diterapkan pada perintah autentikasi saat muncul",
        "th": "ใช้กับพรอมต์การรับรองความถูกต้องในขณะที่ปรากฏขึ้น",
        "vi": "Áp dụng cho lời nhắc xác thực khi nó xuất hiện"
    },
    "Applied to the date and time while opening the password prompt": {
        "es": "Se aplica a la fecha y hora al abrir el indicador de contraseña",
        "fr": "Appliqué à la date et à l'heure lors de l'ouverture de la saisie du mot de passe",
        "de": "Wird auf Datum und Uhrzeit angewendet, während die Passworteingabe geöffnet wird",
        "it": "Applicato alla data e all'ora durante l'apertura del prompt della password",
        "pt": "Aplicado à data e hora ao abrir o campo de senha",
        "ru": "Применяется к дате и времени при открытии окна ввода пароля",
        "zh": "在显示密码输入框时应用于日期和时间",
        "ja": "パスワード入力画面を開く際、日付と時刻に適用されます",
        "ko": "암호 입력창이 열리는 동안 날짜와 시간에 적용됩니다",
        "ar": "تطبق على التاريخ والوقت أثناء فتح حقل كلمة المرور",
        "hi": "पासवर्ड संकेत खोलते समय दिनांक और समय पर लागू होता है",
        "tr": "Parola istemi açılırken tarih ve saate uygulanır",
        "nl": "Toegepast op de datum en tijd tijdens het openen van de wachtwoordprompt",
        "pl": "Stosowane do daty i godziny podczas otwierania monitu o hasło",
        "sv": "Tillämpas på datum och tid när lösenordsfältet öppnas",
        "da": "Anvendes på dato og tid, når adgangskodefeltet åbnes",
        "no": "Brukes på dato og tid når passordfeltet åpnes",
        "fi": "Käytetään päivämäärässä ja ajassa, kun salasanakenttää avataan",
        "el": "Εφαρμόζεται στην ημερομηνία και την ώρα κατά το άνοιγμα του πλαισίου κωδικού",
        "he": "מוחל על התאריך והשעה בעת פתיחת תיבת הסיסמה",
        "id": "Diterapkan pada tanggal dan waktu saat membuka perintah kata sandi",
        "th": "ใช้กับวันที่และเวลาขณะเปิดช่องใส่รหัสผ่าน",
        "vi": "Áp dụng cho ngày và giờ trong khi mở hộp nhập mật khẩu"
},
    "Blank Timeout": {
        "es": "Tiempo de espera de apagado de pantalla",
        "fr": "Délai d'extinction de l'écran",
        "de": "Ausschaltverzögerung",
        "it": "Timeout di spegnimento schermo",
        "pt": "Tempo limite para desligar a tela",
        "ru": "Тайм-аут выключения экрана",
        "zh": "关闭屏幕超时",
        "ja": "画面オフのタイムアウト",
        "ko": "화면 끄기 시간 제한",
        "ar": "مهلة إطفاء الشاشة",
        "hi": "स्क्रीन बंद होने का समय",
        "tr": "Ekran Kapanma Zaman Aşımı",
        "nl": "Uitschakelvertraging",
        "pl": "Czas do wyłączenia ekranu",
        "sv": "Släck skärmen efter",
        "da": "Tidsgrænse for skærmsluk",
        "no": "Tidsavbrudd for skjermslukking",
        "fi": "Näytön sammutuksen aikakatkaisu",
        "el": "Χρονικό όριο απενεργοποίησης οθόνης",
        "he": "פסק זמן לכיבוי המסך",
        "id": "Batas Waktu Mematikan Layar",
        "th": "ระยะเวลาก่อนปิดหน้าจอ",
        "vi": "Thời gian chờ tắt màn hình"
},
    "A complete macOS Sonoma-inspired lockscreen layout (Click user-icon to switch users).": {
        "es": "Diseño completo inspirado en macOS Sonoma (haga clic en el icono de usuario para cambiar de usuario).",
        "fr": "Une disposition complète inspirée de macOS Sonoma (cliquez sur l'icône utilisateur pour changer d'utilisateur).",
        "de": "Ein vollständiges, von macOS Sonoma inspiriertes Sperrbildschirm-Layout (Benutzersymbol anklicken, um Benutzer zu wechseln).",
        "it": "Layout completo ispirato a macOS Sonoma (fare clic sull'icona utente per cambiare utente).",
        "pt": "Layout de tela de bloqueio completo inspirado no macOS Sonoma (clique no ícone do usuário para alternar de usuário).",
        "ru": "Полный макет экрана блокировки в стиле macOS Sonoma (нажмите на иконку пользователя для смены пользователя).",
        "zh": "完整的 macOS Sonoma 启发锁屏布局（点击用户图标以切换用户）。",
        "ja": "完全に macOS Sonoma にインスパイアされたロック画面レイアウト（ユーザーアイコンをクリックしてユーザーを切り替え）。",
        "ko": "macOS Sonoma 스타일의 완전한 잠금 화면 레이아웃(사용자 아이콘을 클릭하여 사용자 전환).",
        "ar": "مظهر كامل لـ قفل الشاشة مستوحى من macOS Sonoma (انقر على أيقونة المستخدم للتبديل بين المستخدمين).",
        "hi": "एक पूर्ण macOS सोनोमा-प्रेरित लॉकस्क्रीन लेआउट (उपयोगकर्ताओं को बदलने के लिए उपयोगकर्ता-आइकन पर क्लिक करें)।",
        "tr": "macOS Sonoma esintili eksiksiz kilit ekranı düzeni (Kullanıcı değiştirmek için kullanıcı simgesine tıklayın).",
        "nl": "Een complete, op macOS Sonoma geïnspireerde lay-out (klik op het gebruikerspictogram om van gebruiker te wisselen).",
        "pl": "Kompletny układ ekranu blokady inspirowany systemem macOS Sonoma (kliknij ikonę użytkownika, aby przełączyć użytkownika).",
        "sv": "En komplett macOS Sonoma-inspirerad låsskärmslayout (klicka på användarikonen för att byta användare).",
        "da": "Et komplet macOS Sonoma-inspireret låseskærms-layout (klik på brugerikonet for at skifte bruger).",
        "no": "Et komplett macOS Sonoma-inspirert låseskjerm-utseende (klikk på brukerikonet for å bytte bruker).",
        "fi": "Täydellinen macOS Sonoma -tyylinen lukitusnäytön asettelu (vaihda käyttäjää napsauttamalla käyttäjäkuvaketta).",
        "el": "Μια πλήρης διάταξη οθόνης κλειδώματος εμπνευσμένη από το macOS Sonoma (κάντε κλικ στο εικονίδιο χρήστη για εναλλαγή χρηστών).",
        "he": "פריסת מסך נעילה מלאה בהשראת macOS Sonoma (לחץ על סמל המשתמש כדי להחליף משתמש).",
        "id": "Tata letak layar kunci lengkap yang terinspirasi macOS Sonoma (Klik ikon pengguna untuk beralih pengguna).",
        "th": "เค้าโครงหน้าจอล็อกที่ได้รับแรงบันดาลใจจาก macOS Sonoma อย่างสมบูรณ์ (คลิกไอคอนผู้ใช้เพื่อสลับผู้ใช้)",
        "vi": "Bố cục màn hình khóa lấy cảm hứng từ macOS Sonoma hoàn chỉnh (Nhấp vào biểu tượng người dùng để chuyển đổi người dùng)."
    },
    "macOS Sonoma-style clock over the classic, GNOME-compliant layout and flow.": {
        "es": "Reloj estilo macOS Sonoma sobre el diseño y flujo clásico compatible con GNOME.",
        "fr": "Horloge de style macOS Sonoma sur la disposition et le flux classiques conformes à GNOME.",
        "de": "Uhr im macOS-Sonoma-Stil über dem klassischen, GNOME-konformen Layout und Ablauf.",
        "it": "Orologio in stile macOS Sonoma sul layout e flusso classico conforme a GNOME.",
        "pt": "Relógio estilo macOS Sonoma sobre o layout e fluxo clássico compatível com o GNOME.",
        "ru": "Часы в стиле macOS Sonoma поверх стандартного интерфейса и логики работы GNOME.",
        "zh": "在传统的 GNOME 布局和流程之上显示 macOS Sonoma 风格的时钟。",
        "ja": "標準の GNOME レイアウトとフロー上に macOS Sonoma 風の時計を表示します。",
        "ko": "기존 GNOME 레이아웃 및 흐름 위에 macOS Sonoma 스타일 시계 적용.",
        "ar": "ساعة بنمط macOS Sonoma فوق واجهة مستخدم وسير عمل GNOME الافتراضي.",
        "hi": "क्लासिक, जीनोम-अनुरूप लेआउट और फ्लो पर macOS सोनोमा-शैली की घड़ी।",
        "tr": "Klasik, GNOME uyumlu düzen ve akış üzerinde macOS Sonoma tarzı saat.",
        "nl": "Klok in macOS Sonoma-stijl over de klassieke, met GNOME compatibele lay-out en stroom.",
        "pl": "Zegar w stylu macOS Sonoma nałożony na klasyczny, zgodny z GNOME układ i przepływ.",
        "sv": "macOS Sonoma-stilklocka över den traditionella GNOME-kompatibla layouten och flödet.",
        "da": "Ur i macOS Sonoma-stil over det traditionelle GNOME-kompatible layout og flow.",
        "no": "Klokke i macOS Sonoma-stil over den tradisjonelle GNOME-kompatible layouten og flyten.",
        "fi": "macOS Sonoma -tyylinen kello perinteisen, GNOME-yhteensopivan asettelun ja kulun päällä.",
        "el": "Ρολόι στυλ macOS Sonoma πάνω από την κλασική, συμβατή με το GNOME διάταξη και ροή.",
        "he": "שעון בסגנון macOS Sonoma מעל פריסת וזרימת ה־GNOME הקלאסית המוכרת.",
        "id": "Jam bergaya macOS Sonoma di atas tata letak dan alur klasik yang sesuai dengan GNOME.",
        "th": "นาฬิกาสไตล์ macOS Sonoma บนเค้าโครงและโฟลว์การทำงานของ GNOME แบบดั้งเดิม",
        "vi": "Đồng hồ kiểu macOS Sonoma trên bố cục và luồng hoạt động chuẩn GNOME cổ điển."
    },
    "Unlock Crossfade": {
        "es": "Desvanecimiento de desbloqueo",
        "fr": "Fondu de déverrouillage",
        "de": "Entsperr-Ausblendung",
        "it": "Dissolvenza sblocco",
        "pt": "Esmaecimento de desbloqueio",
        "ru": "Затухание при разблокировке",
        "zh": "解锁渐变",
        "ja": "ロック解除クロスフェード",
        "ko": "잠금 해제 크로스페이드",
        "ar": "تلاشي فتح القفل",
        "hi": "अनलॉक क्रॉसफ़ेड",
        "tr": "Kilit Açma Solması",
        "nl": "Ontgrendelfade",
        "pl": "Przenikanie odblokowania",
        "sv": "Avtoning vid upplåsning",
        "da": "Udtoning ved oplåsning",
        "no": "Avtoning ved opplåsing",
        "fi": "Lukituksen avauksen häivytys",
        "el": "Ξεθώριασμα ξεκλειδώματος",
        "he": "עמעום פתיחה",
        "id": "Pudar Buka Kunci",
        "th": "การจางหายขณะปลดล็อก",
        "vi": "Làm mờ khi mở khóa"
    },
    "Crossfade the lockscreen with desktop when unlocking (automatically disabled in Power Saver mode).": {
        "es": "Desvanece la pantalla de bloqueo con el escritorio al desbloquear (desactivado automáticamente en modo de ahorro de energía).",
        "fr": "Estomper l'écran de verrouillage avec le bureau lors du déverrouillage (automatiquement désactivé en mode économie d'énergie).",
        "de": "Blendet den Sperrbildschirm beim Entsperren mit dem Desktop aus (im Energiesparmodus automatisch deaktiviert).",
        "it": "Dissolve la schermata di blocco con il desktop durante lo sblocco (automaticamente disabilitato in modalità risparmio energetico).",
        "pt": "Esmaece a tela de bloqueio com a área de trabalho ao desbloquear (desativado automaticamente no modo de economia de energia).",
        "ru": "Плавное затухание экрана блокировки при переходе к рабочему столу при разблокировке (автоматически отключается в режиме энергосбережения).",
        "zh": "解锁时使锁屏渐变至桌面（在省电模式下自动禁用）。",
        "ja": "ロック解除時にロック画面をデスクトップとクロスフェードします（バッテリーセーバーモードでは自動的に無効になります）。",
        "ko": "잠금 해제 시 잠금 화면을 데스크톱과 크로스페이드합니다(절전 모드에서는 자동으로 비활성화됨).",
        "ar": "تلاشي شاشة القفل مع سطح المكتب عند فتح القفل (يتم إيقاف تشغيله تلقائيًا في وضع توفير الطاقة).",
        "hi": "अनलॉक करते समय डेस्कटॉप के साथ锁屏 को क्रॉसफ़ेड करें (बैटरी सेवर मोड में स्वचालित रूप से अक्षम)।",
        "tr": "Kilit açılırken kilit ekranını masaüstüyle yavaşça soldurur (Güç Tasarrufu modunda otomatik olarak devre dışı bırakılır).",
        "nl": "Laat het vergrendelscherm vervagen met het bureaublad bij het ontgrendelen (automatisch uitgeschakeld in de energiebesparingsmodus).",
        "pl": "Przenika ekran blokady z pulpitem podczas odblokowywania (automatycznie wyłączane w trybie oszczędzania energii).",
        "sv": "Tona ut låsskärmen med skrivbordet när du låser upp (inaktiveras automatiskt i energisparläge).",
        "da": "Tone låseskærmen ud med skrivebordet under oplåsning (deaktiveres automatisk i strømsparetilstand).",
        "no": "Tone ut låseskjermen med skrivebordet ved opplåsing (deaktiveres automatisk i strømsparingsmodus).",
        "fi": "Häivyttää lukitusnäytön työpöydän kanssa lukitusta avattaessa (poistetaan automaattisesti käytöstä virransäästötilassa).",
        "el": "Ξεθωριάζει την οθόνη κλειδώματος με την επιφάνεια εργασίας κατά το ξεκλείδωμα (απενεργοποιείται αυτόματα στη λειτουργία εξοικονόμησης ενέργειας).",
        "he": "עמעום מסך הנעילה יחד עם שולחן העבודה בעת פתיחת הנעילה (מנוטרל אוטומטית במצב חיסכון בחשמל).",
        "id": "Pudarkan layar kunci dengan desktop saat membuka kunci (dinonaktifkan secara otomatis dalam mode Penghemat Daya).",
        "th": "จางหน้าจอล็อกออกพร้อมกับเดสก์ท็อปเมื่อปลดล็อก (ปิดใช้งานโดยอัตโนมัติในโหมดประหยัดพลังงาน)",
        "vi": "Làm mờ màn hình khóa với màn hình chính khi mở khóa (tự động tắt trong chế độ Tiết kiệm pin)."
    },
    "Crossfade Speed": {
        "es": "Velocidad de desvanecimiento",
        "fr": "Vitesse du fondu",
        "de": "Ausblendungsgeschwindigkeit",
        "it": "Velocità dissolvenza",
        "pt": "Velocidade do esmaecimento",
        "ru": "Скорость затухания",
        "zh": "渐变速度",
        "ja": "クロスフェード速度",
        "ko": "크로스페이드 속도",
        "ar": "سرعة التلاشي",
        "hi": "क्रॉसफ़ेड गति",
        "tr": "Solma Hızı",
        "nl": "Fadesnelheid",
        "pl": "Prędkość przenikania",
        "sv": "Avtoningshastighet",
        "da": "Udtoningshastighed",
        "no": "Avtoningshastighet",
        "fi": "Häivytysnopeus",
        "el": "Ταχύτητα ξεθωριάσματος",
        "he": "מהירות עמעום",
        "id": "Kecepatan Pudar",
        "th": "ความเร็วในการจางหาย",
        "vi": "Tốc độ làm mờ"
    },
    "Cupertino Unlock Fade": {
        "es": "Desvanecimiento de desbloqueo Cupertino",
        "fr": "Fondu de déverrouillage Cupertino",
        "de": "Cupertino Entsperr-Ausblendung",
        "it": "Dissolvenza sblocco Cupertino",
        "pt": "Esmaecimento de desbloqueio Cupertino",
        "ru": "Затухание разблокировки Купертино",
        "zh": "库比蒂诺解锁淡出",
        "ja": "クパチーノのロック解除フェード",
        "ko": "Cupertino 잠금 해제 페이드",
        "ar": "تلاشي فتح قفل كوبرتينו",
        "hi": "क्यूपर्टिनो अनलॉक फ़ेड",
        "tr": "Cupertino Kilit Açma Solması",
        "nl": "Cupertino ontgrendelfade",
        "pl": "Zanikanie odblokowania Cupertino",
        "sv": "Cupertino-avtoning vid upplåsning",
        "da": "Cupertino-udtoning ved oplåsning",
        "no": "Cupertino-avtoning ved opplåsing",
        "fi": "Cupertinon lukituksen avauksen häivytys",
        "el": "Ξεθώριασμα ξεκλειδώματος Cupertino",
        "he": "עמעום פתיחה בסגנון קופרטינו",
        "id": "Pudar Buka Kunci Cupertino",
        "th": "การจางหายขณะปลดล็อกคูเปอร์ติโน",
        "vi": "Làm mờ khi mở khóa Cupertino"
    },
    "Fade out the lock screen with a panel slide-in when unlocking.": {
        "es": "Desvanece la pantalla de bloqueo con un deslizamiento del panel al desbloquear.",
        "fr": "Estomper l'écran de verrouillage avec un glissement du tableau de bord lors du déverrouillage.",
        "de": "Blendet den Sperrbildschirm aus und das Panel beim Entsperren ein.",
        "it": "Dissolve la schermata di blocco con uno scorrimento del pannello durante lo sblocco.",
        "pt": "Esmaece a tela de bloqueio com um deslizamento do painel ao desbloquear.",
        "ru": "Плавное исчезновение экрана блокировки со слайд-эффектом панели при разблокировке.",
        "zh": "解锁时使锁屏淡出，同时面板滑入。",
        "ja": "ロック解除時に、パネルのスライドインと同時にロック画面をフェードアウトします。",
        "ko": "잠금 해제 시 패널이 슬라이드인되며 잠금 화면이 서서히 사라집니다.",
        "ar": "تلاشي شاشة القفل مع انزلاق اللوحة للداخل عند فتح القفل.",
        "hi": "अनलॉक करते समय पैनल के स्लाइड-इन के साथ लॉक स्क्रीन को फ़ेड आउट करें।",
        "tr": "Kilit açılırken panelin içeri kaymasıyla kilit ekranını yavaşça soldurur.",
        "nl": "Laat het vergrendelscherm vervagen met een inschuivend paneel bij het ontgrendelen.",
        "pl": "Wygasza ekran blokady z wsuwającym się panelem podczas odblokowywania.",
        "sv": "Tona ut låsskärmen med en glidande panel när du låser upp.",
        "da": "Tone låseskærmen ud med et indglidende panel under oplåsning.",
        "no": "Tone ut låseskjermen med et innskliende panel ved opplåsing.",
        "fi": "Häivyttää lukitusnäytön paneelin liukuessa sisään lukitusta avattaessa.",
        "el": "Σταδιακό σβήσιμο της οθόνης κλειδώματος με ολίσθηση του πίνακα κατά το ξεκλείδωμα.",
        "he": "עמעום מסך הנעילה יחד עם החלקת הפנל פנימה בעת פתיחת הנעילה.",
        "id": "Pudarkan layar kunci dengan panel yang meluncur masuk saat membuka kunci.",
        "th": "จางหน้าจอล็อกออกพร้อมกับแผงที่เลื่อนเข้ามาเมื่อปลดล็อก",
        "vi": "Làm mờ màn hình khóa với hiệu ứng bảng trượt vào khi mở khóa."
    },
    "Choose between Legacy and Cupertino styles": {
        "es": "Elegir entre los estilos clásico y Cupertino",
        "fr": "Choisir entre le style classique et le style Cupertino",
        "de": "Zwischen dem klassischen und dem Cupertino-Stil wählen",
        "it": "Scegli tra lo stile classico e quello Cupertino",
        "pt": "Escolha entre os estilos clássico e Cupertino",
        "ru": "Выбор между классическим стилем и стилем Cupertino",
        "zh": "在经典与 Cupertino 样式之间选择",
        "ja": "クラシックとクパチーノスタイルから選択",
        "ko": "클래식과 쿠퍼티노 스타일 중 선택",
        "ar": "اختر بين النمط الكلاسيكي ونمط Cupertino",
        "hi": "क्लासिक और क्यूपर्टिनो शैलियों के बीच चयन करें",
        "tr": "Klasik ve Cupertino stilleri arasından seçim yapın",
        "nl": "Kies tussen de klassieke stijl of Cupertino",
        "pl": "Wybierz między stylem klasycznym a Cupertino",
        "sv": "Välj mellan klassisk stil och Cupertino",
        "da": "Vælg mellem klassisk stil og Cupertino",
        "no": "Velg mellom klassisk stil og Cupertino",
        "fi": "Valitse klassisen ja Cupertino-tyylin välillä",
        "el": "Επιλογή μεταξύ του κλασικού στυλ και του στυλ Cupertino",
        "he": "בחירה בין הסגנון הקלאסי לבין סגנון קופרטינו",
        "id": "Pilih antara gaya Klasik dan Cupertino",
        "th": "เลือกระหว่างสไตล์คลาสสิกและสไตล์คูเปอร์ติโน",
        "vi": "Chọn giữa phong cách Cổ điển và Cupertino"
},
    "Choose how the lock screen clock leaves and how the password prompt enters.": {
        "es": "Elige cómo desaparece el reloj de la pantalla de bloqueo y cómo aparece el indicador de contraseña.",
        "fr": "Définit la façon dont l'horloge disparaît et l'invite de mot de passe apparaît.",
        "de": "Legt fest, wie die Sperrbildschirmuhr ausgeblendet und die Passworteingabe eingeblendet wird.",
        "it": "Scegli come scompare l'orologio della schermata di blocco e come appare il prompt della password.",
        "pt": "Escolha como o relógio da tela de bloqueio desaparece e como o campo de senha aparece.",
        "ru": "Выбор анимации скрытия часов и появления окна ввода пароля.",
        "zh": "选择锁屏时钟消失及密码输入框出现的动画样式。",
        "ja": "ロック画面の時計が消える時のアニメーションと、パスワード入力画面が表示される時のアニメーションを選択します。",
        "ko": "잠금 화면 시계가 사라질 때와 암호 입력창이 나타날 때의 애니메이션을 선택합니다.",
        "ar": "اختر حركة اختفاء ساعة قفل الشاشة وحركة ظهور حقل كلمة المرور.",
        "hi": "चुनें कि लॉक स्क्रीन घड़ी कैसे गायब होती है और पासवर्ड प्रॉम्प्ट कैसे प्रवेश करता है।",
        "tr": "Kilit ekranı saatinin nasıl kaybolacağını ve parola isteminin nasıl görüneceğini seçin.",
        "nl": "Kies hoe de klok van het vergrendelscherm verdwijnt en het wachtwoordveld verschijnt.",
        "pl": "Wybierz, jak zegar ekranu blokady znika i jak pojawia się monit o hasło.",
        "sv": "Välj hur låsskärmens klocka försvinner och lösenordsfältet visas.",
        "da": "Vælg, hvordan låseskærmens ur forsvinder, og adgangskodefeltet vises.",
        "no": "Velg hvordan låseskjermens klokke forsvinner og passordfeltet vises.",
        "fi": "Valitse, miten lukitusnäytön kello poistuu ja miten salasanakenttä tulee näkyviin.",
        "el": "Επιλέξτε πώς εξαφανίζεται το ρολόι της οθόνης κλειδώματος και πώς εμφανίζεται το πλαίσιο κωδικού.",
        "he": "בחר כיצד שעון מסך הנעילה נעלם וכיצד מופיעה תיבת הסיסמה.",
        "id": "Pilih bagaimana jam layar kunci keluar dan bagaimana perintah kata sandi masuk.",
        "th": "เลือกว่าจะให้นาฬิกาบนหน้าจอล็อกหายไปอย่างไรและให้ช่องใส่รหัสผ่านแสดงขึ้นมาอย่างไร",
        "vi": "Chọn cách đồng hồ màn hình khóa biến mất và hộp nhập mật khẩu xuất hiện."
},
    "Clock Animation": {
        "es": "Animación del reloj",
        "fr": "Animation d'horloge",
        "de": "Uhranimation",
        "it": "Animazione dell'orologio",
        "pt": "Animação de relógio",
        "ru": "Анимация часов",
        "zh": "时钟动画",
        "ja": "時計アニメーション",
        "ko": "시계 애니메이션",
        "ar": "الرسوم المتحركة على مدار الساعة",
        "hi": "घड़ी एनीमेशन",
        "tr": "Saat Animasyonu",
        "nl": "Klokanimatie",
        "pl": "Animacja zegara",
        "sv": "Klockanimering",
        "da": "Ur animation",
        "no": "Klokkeanimasjon",
        "fi": "Kello-animaatio",
        "el": "Κινούμενα σχέδια ρολογιού",
        "he": "אנימציית שעון",
        "id": "Animasi Jam",
        "th": "ภาพเคลื่อนไหวนาฬิกา",
        "vi": "Hoạt hình đồng hồ"
    },
    "Configuration": {
        "es": "Configuración",
        "fr": "Configuration",
        "de": "Konfiguration",
        "it": "Configurazione",
        "pt": "Configuração",
        "ru": "Конфигурация",
        "zh": "配置",
        "ja": "構成",
        "ko": "구성",
        "ar": "إعدادات",
        "hi": "विन्यास",
        "tr": "Yapılandırma",
        "nl": "Configuratie",
        "pl": "Konfiguracja",
        "sv": "Konfiguration",
        "da": "Konfiguration",
        "no": "Konfigurasjon",
        "fi": "Kokoonpano",
        "el": "Διαμόρφωση",
        "he": "תְצוּרָה",
        "id": "Konfigurasi",
        "th": "การกำหนดค่า",
        "vi": "Cấu hình"
    },
    "Consider supporting its development!": {
        "es": "¡Considere apoyar su desarrollo!",
        "fr": "Pensez à soutenir son développement !",
        "de": "Erwägen Sie, seine Entwicklung zu unterstützen!",
        "it": "Valuta di sostenere il suo sviluppo!",
        "pt": "Considere apoiar o seu desenvolvimento!",
        "ru": "Подумайте о поддержке его развития!",
        "zh": "考虑支持它的发展！",
        "ja": "その開発をサポートすることを検討してください。",
        "ko": "개발 지원을 고려해보세요!",
        "ar": "النظر في دعم تطويرها!",
        "hi": "इसके विकास का समर्थन करने पर विचार करें!",
        "tr": "Gelişimini desteklemeyi düşünün!",
        "nl": "Overweeg om de ontwikkeling ervan te ondersteunen!",
        "pl": "Rozważ wsparcie jego rozwoju!",
        "sv": "Överväg att stödja dess utveckling!",
        "da": "Overvej at støtte dens udvikling!",
        "no": "Vurder å støtte utviklingen!",
        "fi": "Harkitse sen kehittämisen tukemista!",
        "el": "Σκεφτείτε να υποστηρίξετε την ανάπτυξή του!",
        "he": "שקול לתמוך בפיתוחו!",
        "id": "Pertimbangkan untuk mendukung pengembangannya!",
        "th": "พิจารณาสนับสนุนการพัฒนาของมัน!",
        "vi": "Hãy xem xét hỗ trợ sự phát triển của nó!"
    },
    "Control when the screen turns off or blanks on the lock screen.": {
        "es": "Controla cuándo se apaga o se oscurece la pantalla en la pantalla de bloqueo.",
        "fr": "Détermine quand l'écran s'éteint ou s'assombrit sur l'écran de verrouillage.",
        "de": "Steuert das Ausschalten oder Abdunkeln des Bildschirms im Sperrbildschirm.",
        "it": "Controlla quando lo schermo si spegne o si oscura nella schermata di blocco.",
        "pt": "Controla quando a tela desliga ou escurece na tela de bloqueio.",
        "ru": "Управление временем выключения или гашения экрана при блокировке.",
        "zh": "控制锁屏时屏幕何时关闭或变黑。",
        "ja": "ロック画面で画面がオフになったり消灯したりするタイミングを制御します。",
        "ko": "잠금 화면에서 화면이 꺼지거나 대기 상태로 들어가는 시간을 제어합니다.",
        "ar": "التحكم في وقت إطفاء الشاشة أو تعتيمها على شاشة القفل.",
        "hi": "नियंत्रित करें कि लॉक स्क्रीन पर स्क्रीन कब बंद या धुंधली होती है।",
        "tr": "Kilit ekranında ekranın ne zaman kapanacağını veya kararacağını kontrol edin.",
        "nl": "Regelt wanneer het scherm wordt uitgeschakeld of zwart wordt op het vergrendelscherm.",
        "pl": "Określa, kiedy ekran wyłącza się lub wygasza na ekranie blokady.",
        "sv": "Styr när skärmen stängs av eller släcks på låsskärmen.",
        "da": "Styr, hvornår skærmen slukker eller slukkes på låseskærmen.",
        "no": "Kontroller når skjermen slås av eller slukkes på låseskjermen.",
        "fi": "Määrittää, milloin näyttö sammuu tai himmenee lukitusnäytöllä.",
        "el": "Ελέγχει πότε η οθόνη απενεργοποιείται ή μαυρίζει στην οθόνη κλειδώματος.",
        "he": "שליטה מתי המסך יכבה או יוחשך במסך הנעيلة.",
        "id": "Kontrol kapan layar mati atau kosong di layar kunci.",
        "th": "ควบคุมการดับหรือปิดหน้าจอเมื่ออยู่บนหน้าจอล็อก",
        "vi": "Kiểm soát thời điểm màn hình tắt hoặc tối đi trên màn hình khóa."
},
    "Cupertino": {
        "es": "Cupertino",
        "fr": "Cupertino",
        "de": "Cupertino",
        "it": "Cupertino",
        "pt": "Cupertino",
        "ru": "Купертино",
        "zh": "库比蒂诺",
        "ja": "クパチーノ",
        "ko": "쿠퍼티노",
        "ar": "كوبرتينو",
        "hi": "क्यूपर्टिनो",
        "tr": "Cupertino",
        "nl": "Cupertino",
        "pl": "Cupertino",
        "sv": "Cupertino",
        "da": "Cupertino",
        "no": "Cupertino",
        "fi": "Cupertino",
        "el": "Κουπερτίνο",
        "he": "קופרטינו",
        "id": "Cupertino",
        "th": "คูเปอร์ติโน",
        "vi": "Cupertino"
    },
    "Enjoying this extension?": {
        "es": "¿Disfrutas de esta extensión?",
        "fr": "Vous appréciez cette extension ?",
        "de": "Gefällt Ihnen diese Erweiterung?",
        "it": "Ti piace questa estensione?",
        "pt": "Está gostando desta extensão?",
        "ru": "Нравится это расширение?",
        "zh": "喜欢这个扩展吗？",
        "ja": "この拡張機能は気に入りましたか？",
        "ko": "이 확장 프로그램이 마음에 드시나요?",
        "ar": "هل تستمتع بهذا الامتداد؟",
        "hi": "इस विस्तार का आनंद ले रहे हैं?",
        "tr": "Bu uzantıyı beğeniyor musunuz?",
        "nl": "Bevalt deze extensie?",
        "pl": "Podoba Ci się to rozszerzenie?",
        "sv": "Gillar du det här tillägget?",
        "da": "Glad for denne udvidelse?",
        "no": "Liker du denne utvidelsen?",
        "fi": "Pidätkö tästä laajennuksesta?",
        "el": "Σας αρέσει αυτή η επέκταση;",
        "he": "נהנה מהתוספת הזו?",
        "id": "Menikmati ekstensi ini?",
        "th": "ชอบส่วนขยายนี้ไหม?",
        "vi": "Bạn có thích tiện ích mở rộng này?"
},
    "Escape to Sleep / Suspend": {
        "es": "Escape para apagar pantalla / suspender",
        "fr": "Échap pour éteindre l'écran / mettre en veille",
        "de": "Escape für Bildschirm aus / Bereitschaft",
        "it": "Esc per spegnere lo schermo / sospendere",
        "pt": "Esc para desligar tela / suspender",
        "ru": "Esc для выключения экрана / режима ожидания",
        "zh": "Esc 键用于关闭屏幕/挂起",
        "ja": "Escで画面オフ/サスペンド",
        "ko": "Esc로 화면 끄기/절전",
        "ar": "Esc لإطفاء الشاشة / التعليق",
        "hi": "स्क्रीन बंद / निलंबित करने के लिए Esc",
        "tr": "Ekranı Kapatmak / Askıya Almak için Esc",
        "nl": "Esc voor scherm uitschakelen / stand-by",
        "pl": "Esc, aby wyłączyć ekran / uśpić",
        "sv": "Esc för att släcka skärmen / vänteläge",
        "da": "Esc for at slukke skærmen / hviletilstand",
        "no": "Esc for å slå av skjermen / hvilemodus",
        "fi": "Esc näytön sammuttamiseksi / valmiustilaan",
        "el": "Esc για απενεργοποίηση οθόνης / αναστολή",
        "he": "Esc לכיβอย מסך / השהיה",
        "id": "Esc untuk mematikan layar / sleep",
        "th": "Esc เพื่อปิดหน้าจอ / พักเครื่อง",
        "vi": "Esc để tắt màn hình / tạm dừng"
},
    "Extension Repo": {
        "es": "Repositorio de extensión",
        "fr": "Dépôt d'extensions",
        "de": "Erweiterungs-Repo",
        "it": "Deposito estensioni",
        "pt": "Repositório de extensão",
        "ru": "Репозиторий расширений",
        "zh": "扩展仓库",
        "ja": "拡張機能リポジトリ",
        "ko": "확장 레포",
        "ar": "تمديد الريبو",
        "hi": "एक्सटेंशन रेपो",
        "tr": "Uzantı Deposu",
        "nl": "Extensie Repo",
        "pl": "Repozytorium rozszerzeń",
        "sv": "Förlängning Repo",
        "da": "Udvidelse Repo",
        "no": "Utvidelse Repo",
        "fi": "Laajennus Repo",
        "el": "Επέκταση Repo",
        "he": "Repo של הרחבה",
        "id": "Repo Ekstensi",
        "th": "ส่วนขยาย Repo",
        "vi": "Kho lưu trữ tiện ích mở rộng"
    },
    "Home": {
        "es": "Inicio",
        "fr": "Accueil",
        "de": "Startseite",
        "it": "Home",
        "pt": "Início",
        "ru": "Главная",
        "zh": "主页",
        "ja": "ホーム",
        "ko": "홈",
        "ar": "الرئيسية",
        "hi": "मुख्य पृष्ठ",
        "tr": "Ana Sayfa",
        "nl": "Home",
        "pl": "Ekran główny",
        "sv": "Hem",
        "da": "Hjem",
        "no": "Hjem",
        "fi": "Aloitus",
        "el": "Αρχική",
        "he": "בית",
        "id": "Beranda",
        "th": "หน้าแรก",
        "vi": "Trang chủ"
},
    "Keep Screen On": {
        "es": "Mantener pantalla encendida",
        "fr": "Garder l'écran allumé",
        "de": "Bildschirm eingeschaltet lassen",
        "it": "Mantieni schermo acceso",
        "pt": "Manter tela ligada",
        "ru": "Не выключать экран",
        "zh": "保持屏幕开启",
        "ja": "画面をオンのままにする",
        "ko": "화면 켜짐 유지",
        "ar": "إبقاء الشاشة قيد التشغيل",
        "hi": "स्क्रीन चालू रखें",
        "tr": "Ekranı Açık Tut",
        "nl": "Scherm ingeschakeld houden",
        "pl": "Pozostaw ekran włączony",
        "sv": "Håll skärmen på",
        "da": "Hold skærmen tændt",
        "no": "Hold skjermen på",
        "fi": "Pidä näyttö päällä",
        "el": "Διατήρηση της οθόνης ενεργής",
        "he": "השאר את המסך דולק",
        "id": "Tetap Aktifkan Layar",
        "th": "เปิดหน้าจอไว้",
        "vi": "Giữ màn hình luôn bật"
},
    "Ko-fi": {
        "es": "ko-fi",
        "fr": "Kofi",
        "de": "Ko-fi",
        "it": "Ko-fi",
        "pt": "Ko-fi",
        "ru": "Ко-фи",
        "zh": "科菲",
        "ja": "コフィ",
        "ko": "코파이",
        "ar": "كو فاي",
        "hi": "को-फाई",
        "tr": "Ko-fi",
        "nl": "Ko-fi",
        "pl": "Ko-fi",
        "sv": "Ko-fi",
        "da": "Ko-fi",
        "no": "Ko-fi",
        "fi": "Ko-fi",
        "el": "Κο-φι",
        "he": "קו-פי",
        "id": "Ko-fi",
        "th": "โค-ฟี่",
        "vi": "Ko-fi"
    },
    "Legacy": {
        "es": "Clásico",
        "fr": "Classique",
        "de": "Klassisch",
        "it": "Classico",
        "pt": "Clássico",
        "ru": "Классический",
        "zh": "经典",
        "ja": "クラシック",
        "ko": "클래식",
        "ar": "كلاسيكي",
        "hi": "क्लासिक",
        "tr": "Klasik",
        "nl": "Klassiek",
        "pl": "Klasyczny",
        "sv": "Klassisk",
        "da": "Klassisk",
        "no": "Klassisk",
        "fi": "Klassinen",
        "el": "Κλασικό",
        "he": "קלאסי",
        "id": "Klasik",
        "th": "คลาสสิก",
        "vi": "Cổ điển"
},
    "Lockscreen Mode": {
        "es": "Modo de pantalla de bloqueo",
        "fr": "Mode écran de verrouillage",
        "de": "Sperrbildschirmmodus",
        "it": "Modalità schermata di blocco",
        "pt": "Modo de tela de bloqueio",
        "ru": "Режим блокировки экрана",
        "zh": "锁屏模式",
        "ja": "ロック画面モード",
        "ko": "잠금화면 모드",
        "ar": "وضع قفل الشاشة",
        "hi": "लॉकस्क्रीन मोड",
        "tr": "Kilit Ekranı Modu",
        "nl": "Vergrendelschermmodus",
        "pl": "Tryb ekranu blokady",
        "sv": "Låsskärmsläge",
        "da": "Låseskærmtilstand",
        "no": "Låseskjermmodus",
        "fi": "Lukitusnäytön tila",
        "el": "Λειτουργία οθόνης κλειδώματος",
        "he": "מצב מסך נעילה",
        "id": "Mode Layar Kunci",
        "th": "โหมดล็อคหน้าจอ",
        "vi": "Chế độ khóa màn hình"
    },
    "Mode": {
        "es": "Modo",
        "fr": "Mode",
        "de": "Modus",
        "it": "Modalità",
        "pt": "Modo",
        "ru": "Режим",
        "zh": "模式",
        "ja": "モード",
        "ko": "방법",
        "ar": "وضع",
        "hi": "तरीका",
        "tr": "Mod",
        "nl": "Modus",
        "pl": "Tryb",
        "sv": "Läge",
        "da": "Mode",
        "no": "Modus",
        "fi": "tila",
        "el": "Τρόπος",
        "he": "מצב",
        "id": "Mode",
        "th": "โหมด",
        "vi": "Cách thức"
    },
    "Never": {
        "es": "Nunca",
        "fr": "Jamais",
        "de": "Niemals",
        "it": "Mai",
        "pt": "Nunca",
        "ru": "Никогда",
        "zh": "绝不",
        "ja": "一度もない",
        "ko": "절대",
        "ar": "أبداً",
        "hi": "कभी नहीं",
        "tr": "Asla",
        "nl": "Nooit",
        "pl": "Nigdy",
        "sv": "Aldrig",
        "da": "Aldrig",
        "no": "Aldri",
        "fi": "Ei koskaan",
        "el": "Ποτέ",
        "he": "לְעוֹלָם לֹא",
        "id": "Tidak pernah",
        "th": "ไม่เคย",
        "vi": "Không bao giờ"
    },
    "Only keep the screen on if the system is plugged in": {
        "es": "Mantener la pantalla encendida solo en modo CA",
        "fr": "Ne laisser l'écran allumé que sur secteur",
        "de": "Bildschirm nur bei Netzbetrieb eingeschaltet lassen",
        "it": "Mantieni lo schermo acceso solo con alimentazione di rete",
        "pt": "Manter a tela ligada apenas na tomada",
        "ru": "Оставлять экран включенным только при работе от сети",
        "zh": "仅在接通电源时保持屏幕开启",
        "ja": "電源に接続されている場合のみ画面をオンにする",
        "ko": "전원이 연결되어 있는 경우에만 화면 켜짐 유지",
        "ar": "إبقاء الشاشة تعمل فقط عند التوصيل بالكهرباء",
        "hi": "स्क्रीन केवल तब चालू रखें जब सिस्टम प्लग इन हो",
        "tr": "Ekranı yalnızca sistem fişe takılıyken açık tut",
        "nl": "Scherm alleen ingeschakeld laten bij netstroom",
        "pl": "Ekran włączony tylko wtedy, gdy urządzenie jest podłączone do sieci",
        "sv": "Håll bara skärmen igång vid nätström",
        "da": "Hold kun skærmen tændt ved netstrøm",
        "no": "Hold skjermen på bare ved nätstrøm",
        "fi": "Pidä näyttö päällä vain verkkovirralla",
        "el": "Διατήρηση της οθόνης ενεργής μόνο κατά τη σύνδεση στο ρεύμα",
        "he": "השאר את המסך פעיל רק בחיבור לחשמל",
        "id": "Hanya biarkan layar menyala saat menggunakan daya AC",
        "th": "เปิดหน้าจอไว้เฉพาะเมื่อเสียบปลั๊กไฟเท่านั้น",
        "vi": "Chỉ giữ màn hình bật khi cắm sạc"
},
    "Only on AC Power": {
        "es": "Solo con alimentación de red",
        "fr": "Uniquement sur secteur",
        "de": "Nur bei Netzbetrieb",
        "it": "Solo con alimentazione di rete",
        "pt": "Apenas na tomada",
        "ru": "Только при работе от сети",
        "zh": "仅在接通电源时",
        "ja": "AC電源使用時のみ",
        "ko": "전원 연결 시에만",
        "ar": "عند التوصيل بالكهرباء فقط",
        "hi": "केवल एसी पावर पर",
        "tr": "Yalnızca AC Gücünde",
        "nl": "Alleen op netstroom",
        "pl": "Tylko przy zasilaniu sieciowym",
        "sv": "Endast vid nätström",
        "da": "Kun ved netstrøm",
        "no": "Kun ved nätstrøm",
        "fi": "Vain verkkovirralla",
        "el": "Μόνο κατά τη σύνδεση στο ρεύμα",
        "he": "רק בחיבור לחשמל",
        "id": "Hanya pada Daya AC",
        "th": "เฉพาะเมื่อเสียบปลั๊กไฟเท่านั้น",
        "vi": "Chỉ khi cắm sạc"
},
    "Open Ko-fi": {
        "es": "Abrir Ko-fi",
        "fr": "Ouvrir Ko-fi",
        "de": "Ko-fi öffnen",
        "it": "Apri Ko-fi",
        "pt": "Abrir Ko-fi",
        "ru": "Открыть Ko-fi",
        "zh": "打开 Ko-fi",
        "ja": "Ko-fi で開く",
        "ko": "Ko-fi 열기",
        "ar": "افتح Ko-fi",
        "hi": "Ko-fi खोलें",
        "tr": "Ko-fi'yi Aç",
        "nl": "Ko-fi openen",
        "pl": "Otwórz Ko-fi",
        "sv": "Öppna Ko-fi",
        "da": "Åbn Ko-fi",
        "no": "Åpne Ko-fi",
        "fi": "Avaa Ko-fi",
        "el": "Άνοιγμα Ko-fi",
        "he": "פתח את Ko-fi",
        "id": "Buka Ko-fi",
        "th": "เปิด Ko-fi",
        "vi": "Mở Ko-fi"
},
    "Open Saweria": {
        "es": "Abrir Saweria",
        "fr": "Ouvrir Saweria",
        "de": "Saweria öffnen",
        "it": "Apri Saweria",
        "pt": "Abrir Saweria",
        "ru": "Открыть Saweria",
        "zh": "打开 Saweria",
        "ja": "Saweria で開く",
        "ko": "Saweria 열기",
        "ar": "افتح Saweria",
        "hi": "Saweria खोलें",
        "tr": "Saweria'yı Aç",
        "nl": "Saweria openen",
        "pl": "Otwórz Saweria",
        "sv": "Öppna Saweria",
        "da": "Åbn Saweria",
        "no": "Åpne Saweria",
        "fi": "Avaa Saweria",
        "el": "Άνοιγμα Saweria",
        "he": "פתח את Saweria",
        "id": "Buka Saweria",
        "th": "เปิด Saweria",
        "vi": "Mở Saweria"
},
    "Open on GitHub": {
        "es": "Abrir en GitHub",
        "fr": "Ouvrir sur GitHub",
        "de": "Auf GitHub öffnen",
        "it": "Apri su GitHub",
        "pt": "Abrir no GitHub",
        "ru": "Открыть на GitHub",
        "zh": "在 GitHub 上打开",
        "ja": "GitHub で開く",
        "ko": "GitHub에서 열기",
        "ar": "افتح على GitHub",
        "hi": "GitHub पर खोलें",
        "tr": "GitHub'da Aç",
        "nl": "Openen op GitHub",
        "pl": "Otwórz w serwisie GitHub",
        "sv": "Öppna på GitHub",
        "da": "Åbn på GitHub",
        "no": "Åpne på GitHub",
        "fi": "Avaa GitHubissa",
        "el": "Άνοιγμα στο GitHub",
        "he": "פתח ב-GitHub",
        "id": "Buka di GitHub",
        "th": "เปิดบน GitHub",
        "vi": "Mở trên GitHub"
},
    "Press Escape on the lock screen to sleep display (or suspend)": {
        "es": "Presione Esc en la pantalla de bloqueo para apagar la pantalla (o suspender)",
        "fr": "Appuyez sur Échap sur l'écran de verrouillage pour éteindre l'écran (ou mettre en veille)",
        "de": "Drücken Sie Escape auf dem Sperrbildschirm, um den Bildschirm auszuschalten (oder in Bereitschaft zu versetzen)",
        "it": "Premi Esc nella schermata di blocco per spegnere lo schermo (o sospendere)",
        "pt": "Pressione Esc na tela de bloco para desligar a tela (ou suspender)",
        "ru": "Нажмите Esc на экране блокировки для выключения экрана (или перехода в режим ожидания)",
        "zh": "在锁定屏幕上按 Esc 键以关闭屏幕（或挂起）",
        "ja": "ロック画面で Esc を押すと、画面をオフ（またはサスペンド）にします",
        "ko": "잠금 화면에서 Esc를 눌러 화면을 끄거나 절전 모드로 전환합니다",
        "ar": "اضغط على Esc في شاشة القفل لإطفاء الشاشة (أو التعليق)",
        "hi": "स्क्रीन बंद करने (या निलंबित करने) के लिए लॉक स्क्रीन पर Esc दबाएं",
        "tr": "Ekranı kapatmak (veya askıya almak) için kilit ekranında Esc tuşuna basın",
        "nl": "Druk op Esc op het vergrendelscherm om het scherm uit te schakelen (of stand-by te zetten)",
        "pl": "Naciśnij Esc na ekranie blokady, aby wyłączyć ekran (lub uśpić)",
        "sv": "Tryck på Esc på låsskärmen för att släcka skärmen (eller gå till vänteläge)",
        "da": "Tryk på Esc på låseskærmen for at slukke skærmen (eller gå i hviletilstand)",
        "no": "Trykk på Esc på låseskjermen for å slå av skjermen (eller gå til hvilemodus)",
        "fi": "Paina Esc-näppäintä lukitusnäytöllä sammuttaaksesi näytön (tai siirtyäksesi valmiustilaan)",
        "el": "Πατήστε Esc στην οθόνη κλειδώματος για απενεργοποίηση της οθόνης (ή αναστολή)",
        "he": "לחץ על Esc במסך הנעילה כדי לכבות את המסך (או להשהות)",
        "id": "Tekan Esc di layar kunci untuk mematikan layar (atau sleep)",
        "th": "กด Esc บนหน้าจอล็อคเพื่อปิดหน้าจอ (หรือพักเครื่อง)",
        "vi": "Nhấn Esc trên màn hình khóa để tắt màn hình (hoặc tạm dừng)"
},
    "Prevent the screen from immediately turning off when locked. The screen will still turn off after the normal timeout duration set in system settings.": {
        "es": "Evita que la pantalla se apague inmediatamente cuando está bloqueada. La pantalla se apagará después del tiempo de espera normal configurado en los ajustes del sistema.",
        "fr": "Empêche l'écran de s'éteindre immédiatement lorsqu'il est verrouillé. L'écran s'éteindra toujours après le délai d'attente normal défini dans les paramètres système.",
        "de": "Verhindert, dass sich der Bildschirm im gesperrten Zustand sofort ausschaltet. Der Bildschirm schaltet sich nach der in den Systemeinstellungen festgelegten normalen Zeitspanne aus.",
        "it": "Evita che lo schermo si spenga immediatamente quando è bloccato. Lo schermo si spegnerà comunque dopo il normale tempo di inattività impostato nelle impostazioni di sistema.",
        "pt": "Evita que a tela se apague imediatamente quando bloqueada. A tela ainda se apagará após o tempo limite normal definido nas configurações do sistema.",
        "ru": "Предотвращает немедленное выключение экрана при блокировке. Экран все равно выключится по истечении обычного времени ожидания, установленного в системных настройках.",
        "zh": "防止锁屏时屏幕立即关闭。屏幕仍会在系统设置中设定的常规超时时间后关闭。",
        "ja": "ロック時に画面がすぐにオフになるのを防ぎます。システム設定で設定された通常のタイムアウト時間が経過すると、画面はオフになります。",
        "ko": "잠금 상태에서 화면이 즉시 꺼지는 것을 방지합니다. 화면은 시스템 설정에 구성된 일반 대기 시간이 지나면 꺼집니다.",
        "ar": "منع الشاشة من الانطفاء فورًا عند القفل. ستستمر الشاشة في الانطفاء بعد فترة المهلة العادية المحددة في إعدادات النظام.",
        "hi": "लॉक होने पर स्क्रीन को तुरंत बंद होने से रोकें. स्क्रीन अभी भी सिस्टम सेटिंग्स में निर्धारित सामान्य समय के बाद बंद हो जाएगी.",
        "tr": "Kilitliyken ekranın hemen kapanmasını önler. Ekran, sistem ayarlarında belirlenen normal süre sonunda kapanmaya devam edecektir.",
        "nl": "Voorkomt dat het scherm onmiddellijk wordt uitgeschakeld bij vergrendeling. Het scherm wordt nog steeds uitgeschakeld na de normale time-outduur ingesteld in de systeeminstellingen.",
        "pl": "Zapobiega natychmiastowemu wyłączaniu ekranu po zablokowaniu. Ekran nadal wyłączy się po normalnym czasie bezczynności ustawionym w ustawieniach systemowych.",
        "sv": "Förhindra att skärmen stängs av omedelbart vid låsning. Skärmen stängs fortfarande av efter den normala tidsgränsen som ställts in i systeminställningarna.",
        "da": "Forhindrer skærmen i at slukke med det samme, når den er låst. Skærmen vil stadig slukke efter det normale tidsrum, der er angivet i systemindstillingerne.",
        "no": "Forhindrer at skjermen slår seg av umiddelbart når den er låst. Skjermen vil fortsatt slå seg av etter den normale tidsgrensen som er angitt i systeminnstillingene.",
        "fi": "Estää näytön sammumisen heti, kun se on lukittu. Näyttö sammuu edelleen järjestelmän asetuksissa määritetyn normaalin ajan kuluttua.",
        "el": "Αποτρέπει την άμεση απενεργοποίηση της οθόνης κατά το κλείδωμα. Η οθόνη θα απενεργοποιηθεί μετά την κανονική διάρκεια που έχει οριστεί στις ρυθμίσεις συστήματος.",
        "he": "מניעת כיבוי מיידי של המסך במצב נעול. המסך עדיין יכבה לאחר זמן ההמתנה הרגיל שהוגדר בהגדרות המערכת.",
        "id": "Mencegah layar langsung mati saat terkunci. Layar akan tetap mati setelah durasi batas waktu normal yang diatur dalam pengaturan sistem.",
        "th": "ป้องกันไม่ให้หน้าจอดับลงทันทีเมื่อล็อกเครื่อง หน้าจอจะยังคงดับลงหลังจากหมดเวลาปกติที่ตั้งค่าไว้ในการตั้งค่าระบบ",
        "vi": "Ngăn màn hình tắt ngay lập tức khi bị khóa. Màn hình sẽ vẫn tắt sau khoảng thời gian chờ thông thường được thiết lập trong cài đặt hệ thống."
    },
    "Prompt Animation": {
        "es": "Animación del indicador de contraseña",
        "fr": "Animation de la saisie du mot de passe",
        "de": "Animation der Passworteingabe",
        "it": "Animazione del prompt della password",
        "pt": "Animação do campo de senha",
        "ru": "Анимация окна ввода пароля",
        "zh": "密码输入框动画",
        "ja": "入力プロンプトのアニメーション",
        "ko": "입력 프롬프트 애니메이션",
        "ar": "حركة حقل كلمة المرور",
        "hi": "पासवर्ड संकेत एनीमेशन",
        "tr": "Parola İstemi Animasyonu",
        "nl": "Animatie van wachtwoordprompt",
        "pl": "Animacja monitu o hasło",
        "sv": "Lösenordsprompt-animering",
        "da": "Adgangskodeprompt-animation",
        "no": "Passordprompt-animasjon",
        "fi": "Salasanakentän animaatio",
        "el": "Κινούμενα σχέδια πλαισίου κωδικού",
        "he": "אניμציית תיבת הסיσמה",
        "id": "Animasi Perintah Kata Sandi",
        "th": "ภาพเคลื่อนไหวของช่องรหัสผ่าน",
        "vi": "Hoạt ảnh của hộp nhập mật khẩu"
},
    "Reset Animations": {
        "es": "Restablecer animaciones",
        "fr": "Réinitialiser les animations",
        "de": "Animationen zurücksetzen",
        "it": "Ripristina animazioni",
        "pt": "Redefinir animações",
        "ru": "Сбросить анимацию",
        "zh": "重置动画",
        "ja": "アニメーションをリセットする",
        "ko": "애니메이션 재설정",
        "ar": "إعادة تعيين الرسوم المتحركة",
        "hi": "एनिमेशन रीसेट करें",
        "tr": "Animasyonları Sıfırla",
        "nl": "Animaties opnieuw instellen",
        "pl": "Zresetuj animacje",
        "sv": "Återställ animationer",
        "da": "Nulstil animationer",
        "no": "Tilbakestill animasjoner",
        "fi": "Palauta animaatiot",
        "el": "Επαναφορά κινούμενων εικόνων",
        "he": "אפס אנימציות",
        "id": "Atur Ulang Animasi",
        "th": "รีเซ็ตภาพเคลื่อนไหว",
        "vi": "Đặt lại ảnh động"
    },
    "Reset animations": {
        "es": "Restablecer animaciones",
        "fr": "Réinitialiser les animations",
        "de": "Animationen zurücksetzen",
        "it": "Reimposta le animazioni",
        "pt": "Redefinir animações",
        "ru": "Сбросить анимацию",
        "zh": "重置动画",
        "ja": "アニメーションをリセットする",
        "ko": "애니메이션 재설정",
        "ar": "إعادة تعيين الرسوم المتحركة",
        "hi": "एनिमेशन रीसेट करें",
        "tr": "Animasyonları sıfırla",
        "nl": "Animaties opnieuw instellen",
        "pl": "Zresetuj animacje",
        "sv": "Återställ animationer",
        "da": "Nulstil animationer",
        "no": "Tilbakestill animasjoner",
        "fi": "Nollaa animaatiot",
        "el": "Επαναφορά κινούμενων εικόνων",
        "he": "אפס אנימציות",
        "id": "Setel ulang animasi",
        "th": "รีเซ็ตภาพเคลื่อนไหว",
        "vi": "Đặt lại hình ảnh động"
    },
    "Resources": {
        "es": "Recursos",
        "fr": "Ressources",
        "de": "Ressourcen",
        "it": "Risorse",
        "pt": "Recursos",
        "ru": "Ресурсы",
        "zh": "资源",
        "ja": "リソース",
        "ko": "자원",
        "ar": "موارد",
        "hi": "संसाधन",
        "tr": "Kaynaklar",
        "nl": "Bronnen",
        "pl": "Zasoby",
        "sv": "Resurser",
        "da": "Ressourcer",
        "no": "Ressurser",
        "fi": "Resurssit",
        "el": "Πόροι",
        "he": "אֶמְצָעִי",
        "id": "Sumber daya",
        "th": "ทรัพยากร",
        "vi": "Tài nguyên"
    },
    "Restore defaults": {
        "es": "Restaurar valores predeterminados",
        "fr": "Restaurer les valeurs par défaut",
        "de": "Standardeinstellungen wiederherstellen",
        "it": "Ripristina le impostazioni predefinite",
        "pt": "Restaurar padrões",
        "ru": "Восстановить настройки по умолчанию",
        "zh": "恢复默认设置",
        "ja": "デフォルトに戻す",
        "ko": "기본값 복원",
        "ar": "استعادة الإعدادات الافتراضية",
        "hi": "डिफॉल्ट्स का पुनःस्थापन",
        "tr": "Varsayılanları geri yükle",
        "nl": "Standaardwaarden herstellen",
        "pl": "Przywróć ustawienia domyślne",
        "sv": "Återställ standardinställningar",
        "da": "Gendan standardindstillinger",
        "no": "Gjenopprett standardinnstillinger",
        "fi": "Palauta oletusasetukset",
        "el": "Επαναφορά προεπιλογών",
        "he": "שחזר ברירת מחדל",
        "id": "Kembalikan default",
        "th": "คืนค่าเริ่มต้น",
        "vi": "Khôi phục mặc định"
    },
    "Saweria": {
        "es": "Saweria",
        "fr": "Sawéria",
        "de": "Saweria",
        "it": "Saweria",
        "pt": "Serraria",
        "ru": "Саверия",
        "zh": "萨维利亚",
        "ja": "サウェリア",
        "ko": "사웨리아",
        "ar": "ساويرية",
        "hi": "सवेरिया",
        "tr": "Saweria",
        "nl": "Saweria",
        "pl": "Saweria",
        "sv": "Saweria",
        "da": "Saweria",
        "no": "Saweria",
        "fi": "Saweria",
        "el": "Saweria",
        "he": "סוריה",
        "id": "Saweria",
        "th": "ซาเวเรีย",
        "vi": "Saweria"
    },
    "Screen Timeout": {
        "es": "Tiempo de espera de pantalla",
        "fr": "Délai d'expiration de l'écran",
        "de": "Bildschirm-Timeout",
        "it": "Timeout dello schermo",
        "pt": "Tempo limite da tela",
        "ru": "Тайм-аут экрана",
        "zh": "屏幕超时",
        "ja": "画面のタイムアウト",
        "ko": "화면 시간 초과",
        "ar": "مهلة الشاشة",
        "hi": "स्क्रीन काल समापन",
        "tr": "Ekran Zaman Aşımı",
        "nl": "Schermtime-out",
        "pl": "Limit czasu ekranu",
        "sv": "Timeout för skärm",
        "da": "Skærm timeout",
        "no": "Skjermtidsavbrudd",
        "fi": "Näytön aikakatkaisu",
        "el": "Λήξη χρονικού ορίου οθόνης",
        "he": "פסק זמן מסך",
        "id": "Batas Waktu Layar",
        "th": "หมดเวลาหน้าจอ",
        "vi": "Hết thời gian chờ màn hình"
    },
    "Time to wait before turning off the screen": {
        "es": "Tiempo de espera antes de apagar la pantalla",
        "fr": "Temps d'attente avant d'éteindre l'écran",
        "de": "Wartezeit vor dem Ausschalten des Bildschirms",
        "it": "Tempo di attesa prima di spegnere lo schermo",
        "pt": "Tempo de espera antes de desligar a tela",
        "ru": "Время ожидания перед выключением экрана",
        "zh": "关闭屏幕前的等待时间",
        "ja": "画面をオフにするまでの待ち時間",
        "ko": "화면이 꺼질 때까지 대기할 시간",
        "ar": "المدة الزمنية sebelum إطفاء الشاشة",
        "hi": "स्क्रीन बंद करने से पहले प्रतीक्षा समय",
        "tr": "Ekran kapatılmadan önce beklenecek süre",
        "nl": "Wachttijd voor het uitschakelen van het scherm",
        "pl": "Czas oczekiwania przed wyłączeniem ekranu",
        "sv": "Väntetid innan skärmen släcks",
        "da": "Vendetid før skærmen slukkes",
        "no": "Ventetid før skjermen slås av",
        "fi": "Odotusaika ennen näytön sammuttamista",
        "el": "Χρόνος αναμονής πριν την απενεργοποίηση της οθόνης",
        "he": "זמן ההמתנה לפני כיבוי המסך",
        "id": "Lama waktu sebelum layar mati",
        "th": "ระยะเวลารอก่อนปิดหน้าจอ",
        "vi": "Thời gian chờ trước khi tắt màn hình"
}
}

PO_HEADER = '''\
# WACK - Sonoma Lockscreen
# Copyright (C) 2026 rinzler69-wastaken
msgid ""
msgstr ""
"Project-Id-Version: {domain}\\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"Language: {lang}\\n"

'''

for lang in MORE:
    po_path = os.path.join(PO_DIR, f"{lang}.po")
    mo_dir  = os.path.join(LOC_DIR, lang, "LC_MESSAGES")
    mo_path = os.path.join(mo_dir, f"{DOMAIN}.mo")

    # Write .po
    content = PO_HEADER.format(domain=DOMAIN, lang=lang)
    content += f'msgid "more"\nmsgstr "{MORE[lang]}"\n\n'
    content += f'msgid "Press Shift + N to view notifications"\nmsgstr "{TOGGLE[lang]}"\n\n'
    content += f'msgid "Sleep prevented by an active process"\nmsgstr "{INHIBIT[lang]}"\n\n'
    
    # Add prefs strings
    for eng_str, lang_map in PREFS_STRINGS.items():
        escaped_eng = eng_str.replace('"', '\\"')
        escaped_trans = lang_map.get(lang, eng_str).replace('"', '\\"')
        content += f'msgid "{escaped_eng}"\nmsgstr "{escaped_trans}"\n\n'
        
    with open(po_path, "w", encoding="utf-8") as f:
        f.write(content)

    # Compile .mo
    os.makedirs(mo_dir, exist_ok=True)
    subprocess.run(["msgfmt", po_path, "-o", mo_path], check=True)
    print(f"  [{lang}] OK")

# Generate .pot file as well
pot_path = os.path.join(PO_DIR, f"{DOMAIN}.pot")
pot_content = PO_HEADER.format(domain=DOMAIN, lang="")
pot_content += 'msgid "more"\nmsgstr ""\n\n'
pot_content += 'msgid "Press Shift + N to view notifications"\nmsgstr ""\n\n'
pot_content += 'msgid "Sleep prevented by an active process"\nmsgstr ""\n\n'
for eng_str in PREFS_STRINGS:
    escaped_eng = eng_str.replace('"', '\\"')
    pot_content += f'msgid "{escaped_eng}"\nmsgstr ""\n\n'
with open(pot_path, "w", encoding="utf-8") as f:
    f.write(pot_content)

print("Done.")
